import type { NextConfig } from "next";
import { wordpressBlogRedirects } from "./src/lib/blog/wordpress-redirects";

const nextConfig: NextConfig = {
  distDir: process.env.NEXT_DIST_DIR || ".next",
  devIndicators: false,
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "econstructinc.com",
        pathname: "/wp-content/uploads/**",
      },
      {
        protocol: "https",
        hostname: "i1.wp.com",
        pathname: "/econstructinc.com/**",
      },
    ],
  },
  turbopack: {
    rules: {
      "*.md": {
        loaders: ["raw-loader"],
        as: "*.js",
      },
    },
  },
  async redirects() {
    return [
      // ── www → apex redirect ──────────────────────────────────
      {
        source: "/:path*",
        has: [{ type: "host", value: "www.econstructhomes.com" }],
        destination: "https://econstructhomes.com/:path*",
        permanent: true,
      },

      // ── Old WordPress portfolio → /projects ──────────────────
      { source: "/construction-projects", destination: "/projects", permanent: true },
      { source: "/construction-projects/page/:n", destination: "/projects", permanent: true },
      { source: "/portfolio", destination: "/projects", permanent: true },
      { source: "/case-studies", destination: "/projects", permanent: true },
      // Individual portfolio pages
      { source: "/portfolio/hutchinson-residence-a-stunning-transformation-by-econstruct", destination: "/projects/hutchinson-cocktails-and-grill", permanent: true },
      { source: "/portfolio/hals-bar-and-grill", destination: "/projects/hals-bar-and-grill", permanent: true },
      { source: "/portfolio/800-degrees", destination: "/projects/800-degrees-woodfired-kitchen", permanent: true },
      { source: "/portfolio/el-pollo-loco-delano-ca", destination: "/projects/el-pollo-loco", permanent: true },
      { source: "/portfolio/koala-tea-westwood-village-ca", destination: "/projects/koala-t-cafe", permanent: true },
      { source: "/portfolio/odd-one-out-boba-tea-shop-delivering-excellence-under-pressure", destination: "/projects/odd-one-out", permanent: true },
      { source: "/portfolio/tea-pot-cafe-a-cozy-retreat-by-econstruct", destination: "/projects/tea-pot-cafe", permanent: true },
      { source: "/portfolio/rothys-melrose-place-a-sustainable-retail-destination-by-econstruct", destination: "/projects/rothys", permanent: true },
      { source: "/portfolio/malingoetz-retail-construction-a-refined-experience-by-econstruct", destination: "/projects/malin-goetz", permanent: true },
      { source: "/portfolio/thom-sweeney-retail-construction-los-angeles", destination: "/projects/thom-sweeney", permanent: true },
      { source: "/portfolio/jersey-mikes-subs-los-angeles-ca", destination: "/projects/jersey-mikes-subs", permanent: true },
      { source: "/portfolio/85c-bakery-cafe-projects", destination: "/projects/85c-bakery-cafe", permanent: true },
      { source: "/portfolio/mechanical-engineering", destination: "/projects/joe-and-the-juice", permanent: true },
      { source: "/portfolio/50-saddlebow-rd-bell-canyon", destination: "/projects/50-saddlebow-rd", permanent: true },
      { source: "/portfolio/54-saddlebow-rd-project-luxury-home-remodeling-los-angeles", destination: "/projects/54-saddlebow-rd", permanent: true },
      { source: "/portfolio/luxury-home-builders-in-los-angeles-transform-hollywood-hills-residence-devista", destination: "/projects/devista-project", permanent: true },
      { source: "/portfolio/marine-avenue-condo-a-sophisticated-oasis-by-econstruct", destination: "/projects/marine-avenue-condo", permanent: true },
      { source: "/portfolio/newcomb-road-2", destination: "/projects/newcomb-road-residence", permanent: true },
      { source: "/portfolio/mulholland-drive-residence-a-contemporary-masterpiece-by-econstruct", destination: "/projects/mulholland-drive-residence", permanent: true },
      // Case study pages
      { source: "/case-study-800-degrees-pizzeria", destination: "/projects/800-degrees-woodfired-kitchen", permanent: true },
      { source: "/case-study-hutchinson-cocktails-grill", destination: "/projects/hutchinson-cocktails-and-grill", permanent: true },
      { source: "/case-study-85c-bakery-cafe-and-distribution-center", destination: "/projects/85c-bakery-cafe", permanent: true },
      { source: "/case-study-50-saddlebow-rd-residential-lift-project", destination: "/projects/50-saddlebow-rd", permanent: true },
      { source: "/luxury-home-builders-los-angeles-hollywood-hills-remodel-case-study", destination: "/projects/devista-project", permanent: true },

      // ── Old service pages → /services ────────────────────────
      { source: "/commercial-construction-los-angeles", destination: "/services", permanent: true },
      { source: "/industrial-construction-los-angeles", destination: "/services", permanent: true },
      { source: "/construction-management-los-angeles", destination: "/services", permanent: true },
      { source: "/general-contracting-los-angeles", destination: "/services", permanent: true },
      { source: "/bar-construction-los-angeles-ca", destination: "/services/restaurant-bar-construction", permanent: true },
      { source: "/restaurant-construction-services-los-angeles-build-your-dream-restaurant", destination: "/services/restaurant-bar-construction", permanent: true },
      { source: "/restaurant-construction-services-los-angeles-build-your-dream-restaurant-with-econstruct", destination: "/services/restaurant-bar-construction", permanent: true },
      { source: "/fast-casual-construction-los-angeles", destination: "/services/restaurant-bar-construction", permanent: true },
      { source: "/casual-dining-construction-los-angeles-build-your-dream-restaurant", destination: "/services/restaurant-bar-construction", permanent: true },
      { source: "/retail-construction-los-angeles", destination: "/services/retail-tenant-improvement", permanent: true },
      { source: "/office-building-ti-contractor-los-angeles", destination: "/services/office-tenant-improvement", permanent: true },
      { source: "/industrial-manufacturing-construction-los-angeles", destination: "/food-distribution-construction/food-manufacturing", permanent: true },
      { source: "/architectural-design-los-angeles", destination: "/services", permanent: true },
      { source: "/interior-design-la", destination: "/services", permanent: true },
      { source: "/turn-key-build-outs-la", destination: "/services", permanent: true },
      { source: "/lease-negotiation-los-angeles", destination: "/services", permanent: true },
      { source: "/equipment-procurement", destination: "/services", permanent: true },
      { source: "/entitlement-expediting", destination: "/services", permanent: true },
      { source: "/additional-services", destination: "/services", permanent: true },
      // Residential service pages
      { source: "/los-angeles-residential-construction-services", destination: "/services", permanent: true },
      { source: "/luxury-home-builders-los-angeles-premier-custom-homes", destination: "/services", permanent: true },
      { source: "/new-home-construction-los-angeles-ca", destination: "/services", permanent: true },
      { source: "/tiny-home-builders-los-angeles", destination: "/blog/tiny-home-builders-los-angeles-build-your-dream-tiny-home-with-econstruct", permanent: true },
      { source: "/adu-construction-los-angeles", destination: "/services", permanent: true },
      { source: "/hillside-lift-construction-los-angeles", destination: "/projects/50-saddlebow-rd", permanent: true },

      // ── Site pages → equivalents ─────────────────────────────
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/contact-page-2", destination: "/contact", permanent: true },
      { source: "/blogs", destination: "/blog", permanent: true },
      { source: "/video", destination: "/blog", permanent: true },
      { source: "/econstruct-reviews", destination: "/reviews", permanent: true },
      { source: "/testimonials", destination: "/reviews", permanent: true },
      { source: "/newleadquestionnaire", destination: "/free-consultation", permanent: true },
      { source: "/new-lead-questionnaire", destination: "/free-consultation", permanent: true },
      { source: "/new-adu-lead", destination: "/free-consultation", permanent: true },
      { source: "/sample", destination: "/", permanent: true },
      { source: "/slider", destination: "/", permanent: true },
      { source: "/thank-you", destination: "/", permanent: true },

      // ── Old WordPress blog posts at root level → /blog/slug ──
      { source: "/essential-guide-to-choosing-skilled-restaurant-contractors-in-los-angeles-for-your-food-service-project", destination: "/blog/choosing-skilled-restaurant-contractors-in-los-angeles-an-essential-guide-for-food-service-projects", permanent: true },
      { source: "/luxury-remodels-la-style-why-econstruct-is-the-custom-home-builder-los-angeles-trusts", destination: "/blog/luxury-remodels-la-style-why-econstruct-is-the-custom-home-builder-los-angeles-trusts", permanent: true },
      { source: "/los-angeles-bar-construction-a-step-by-step-guide-to-success-in-the-city-of-angels", destination: "/blog/los-angeles-bar-construction-a-step-by-step-guide-to-success-in-the-city-of-angels", permanent: true },
      { source: "/the-iron-triangle-of-construction-balancing-quality-speed-and-cost", destination: "/blog/the-iron-triangle-of-construction-balancing-quality-speed-and-cost", permanent: true },
      { source: "/navigating-the-world-of-general-contracting-a-comprehensive-guide-to-hiring-the-right-professional", destination: "/blog/navigating-the-world-of-general-contracting-a-comprehensive-guide-to-hiring-the-right-professional", permanent: true },
      { source: "/homeowners-guide-to-asbestos-and-renovations-essential-information-from-residential-contractors-in-los-angeles", destination: "/blog/homeowners-guide-to-asbestos-and-renovations-essential-information-from-residential-contractors-in-los-angeles", permanent: true },
      { source: "/luxury-home-builders-in-los-angeles-where-dreams-meet-reality", destination: "/blog/luxury-home-builders-in-los-angeles-where-dreams-meet-reality", permanent: true },
      { source: "/econstruct-named-a-top-restaurant-contractor-in-santa-monica-for-2024", destination: "/blog/econstruct-named-a-top-restaurant-contractor-in-santa-monica-for-2024", permanent: true },
      { source: "/eco-smart-home-upgrades-build-a-greener-future-with-econstruct", destination: "/blog/eco-smart-home-upgrades-build-a-greener-future-with-econstruct", permanent: true },
      { source: "/partner-with-top-office-building-ti-contractors-los-angeles-to-design-the-workplace-of-the-future", destination: "/blog/partner-with-top-office-building-ti-contractors-los-angeles-to-design-the-workplace-of-the-future", permanent: true },
      { source: "/top-office-tenant-improvement-contractors-in-los-angeles-transforming-your-space", destination: "/blog/top-office-tenant-improvement-contractors-in-los-angeles-transforming-your-space", permanent: true },
      { source: "/restaurant-construction-los-angeles-800-degrees-pizzeria-case-study-by-econstruct", destination: "/blog/restaurant-construction-los-angeles-800-degrees-pizzeria-case-study-by-econstruct", permanent: true },
      { source: "/econstructs-insight-into-2024-luxury-homeowner-trends-in-los-angeles", destination: "/blog/econstructs-insight-into-2024-luxury-homeowner-trends-in-los-angeles", permanent: true },
      { source: "/top-restaurant-contractor-in-los-angeles-launch-your-dream-restaurant-with-econstruct", destination: "/blog/top-restaurant-contractor-in-los-angeles-launch-your-dream-restaurant-with-econstruct", permanent: true },
      { source: "/tips-for-navigating-office-renovations-in-los-angeles-with-econstruct", destination: "/blog/tips-for-navigating-office-renovations-in-los-angeles-with-econstruct", permanent: true },
      { source: "/7-essentials-for-choosing-the-perfect-restaurant-location", destination: "/blog/7-essentials-for-choosing-the-perfect-restaurant-location", permanent: true },
      { source: "/launching-your-dream-restaurant-insights-from-top-restaurant-contractor-in-los-angeles", destination: "/blog/launching-your-dream-restaurant-insights-from-top-restaurant-contractor-in-los-angeles", permanent: true },
      { source: "/hire-a-top-notch-restaurant-architect-in-los-angeles-the-ultimate-guide", destination: "/blog/hire-a-top-notch-restaurant-architect-in-los-angeles-the-ultimate-guide", permanent: true },
      { source: "/restaurant-kitchens-in-los-angeles-with-econstruct-inc-innovations-in-restaurant-construction", destination: "/blog/restaurant-kitchens-in-los-angeles-with-econstruct-inc-innovations-in-restaurant-construction", permanent: true },
      { source: "/essential-elements-of-construction-blueprints-a-comprehensive-guide", destination: "/blog/essential-elements-of-construction-blueprints-a-comprehensive-guide", permanent: true },
      { source: "/what-is-the-ideal-restaurant-construction-timeline", destination: "/blog/what-is-the-ideal-restaurant-construction-timeline", permanent: true },
      { source: "/what-is-a-conditional-use-permit", destination: "/blog/what-is-a-conditional-use-permit", permanent: true },
      { source: "/architect-designer-contractor-collaboration-the-key-to-successful-construction-projects", destination: "/blog/architect-designer-contractor-collaboration-the-key-to-successful-construction-projects", permanent: true },
      { source: "/decoding-the-permit-and-inspection-process-in-the-city-of-los-angeles", destination: "/blog/decoding-the-permit-and-inspection-process-in-the-city-of-los-angeles", permanent: true },
      { source: "/choosing-skilled-restaurant-contractors-in-los-angeles-an-essential-guide-for-food-service-projects", destination: "/blog/choosing-skilled-restaurant-contractors-in-los-angeles-an-essential-guide-for-food-service-projects", permanent: true },
      { source: "/how-to-engage-with-mep-engineers-for-your-projects", destination: "/blog/how-to-engage-with-mep-engineers-for-your-projects", permanent: true },
      { source: "/restaurant-construction-project-design-plans-a-comprehensive-guide", destination: "/blog/restaurant-construction-project-design-plans-a-comprehensive-guide", permanent: true },
      { source: "/green-innovations-for-your-dream-home-a-guide-by-custom-homebuilders-in-los-angeles", destination: "/blog/green-innovations-for-your-dream-home-a-guide-by-custom-homebuilders-in-los-angeles", permanent: true },
      { source: "/launching-your-dream-restaurant-a-guide-from-a-top-restaurant-contractor-in-los-angeles", destination: "/blog/launching-your-dream-restaurant-insights-from-top-restaurant-contractor-in-los-angeles", permanent: true },
      { source: "/restaurant-construction-in-los-angeles-a-comprehensive-guide-to-project-design-plans-part-2", destination: "/blog/restaurant-construction-in-los-angeles-a-comprehensive-guide-to-project-design-plans-part-2", permanent: true },
      { source: "/elevating-your-hillside-home-finding-the-perfect-hillside-residential-lift-contractor-in-los-angeles", destination: "/blog/elevating-your-hillside-home-finding-the-perfect-hillside-residential-lift-contractor-in-los-angeles", permanent: true },
      { source: "/top-5-mistakes-to-avoid-when-hiring-a-residential-contractor-in-los-angeles", destination: "/blog/top-5-mistakes-to-avoid-when-hiring-a-residential-contractor-in-los-angeles", permanent: true },
      { source: "/your-dream-home-starts-here-site-planning-with-top-residential-contractors-in-los-angeles", destination: "/blog/your-dream-home-starts-here-site-planning-with-top-residential-contractors-in-los-angeles", permanent: true },
      { source: "/tiny-home-builders-los-angeles-build-your-dream-tiny-home-with-econstruct", destination: "/blog/tiny-home-builders-los-angeles-build-your-dream-tiny-home-with-econstruct", permanent: true },
      { source: "/top-10-residential-contractors-in-los-angeles-for-2024-your-ultimate-guide", destination: "/blog/top-10-residential-contractors-in-los-angeles-for-2024-your-ultimate-guide", permanent: true },
      { source: "/build-an-adu-in-los-angeles-2024-cost-breakdown-expert-guide", destination: "/blog/build-an-adu-in-los-angeles-2024-cost-breakdown-expert-guide", permanent: true },
      { source: "/restaurant-construction-in-los-angeles-expert-design-and-build-services", destination: "/blog/restaurant-construction-in-los-angeles-expert-design-and-build-services", permanent: true },
      { source: "/custom-home-builder-in-los-angeles-transform-your-home-with-econstruct", destination: "/blog/custom-home-builder-in-los-angeles-transform-your-home-with-econstruct", permanent: true },
      { source: "/new-home-construction-los-angeles", destination: "/blog/new-home-construction-los-angeles", permanent: true },
      { source: "/residential-contractor-in-los-angeles-expert-home-builders-at-econstruct", destination: "/blog/residential-contractor-in-los-angeles-expert-home-builders-at-econstruct", permanent: true },
      { source: "/plan-check-los-angeles-streamline-your-construction-approval-with-econstruct", destination: "/blog/plan-check-los-angeles-streamline-your-construction-approval-with-econstruct", permanent: true },
      { source: "/food-specialty-construction-los-angeles-expert-builders-for-your-restaurant", destination: "/blog/food-specialty-construction-los-angeles-expert-builders-for-your-restaurant", permanent: true },
      { source: "/residential-construction-los-angeles-transforming-outdated-homes-into-modern-masterpieces", destination: "/blog/residential-construction-los-angeles-transforming-outdated-homes-into-modern-masterpieces", permanent: true },
      { source: "/restaurant-construction-los-angeles-build-your-dream-eatery-with-econstruct", destination: "/blog/restaurant-construction-los-angeles-build-your-dream-eatery-with-econstruct", permanent: true },
      { source: "/design-build-company-los-angeles-streamline-your-construction-with-econstruct", destination: "/blog/design-build-company-los-angeles-streamline-your-construction-with-econstruct", permanent: true },
      { source: "/restaurant-construction-los-angeles-expert-design-build-with-econstruct", destination: "/blog/restaurant-construction-los-angeles-expert-design-build-with-econstruct", permanent: true },
      { source: "/custom-home-builder-los-angeles-design-and-innovation-tailored-to-your-needs", destination: "/blog/custom-home-builder-los-angeles-design-and-innovation-tailored-to-your-needs", permanent: true },
      { source: "/are-tiny-homes-legal-in-los-angeles-everything-you-need-to-know-in-2024", destination: "/blog/are-tiny-homes-legal-in-los-angeles-everything-you-need-to-know-in-2024", permanent: true },
      { source: "/newcomb-road-remodel-a-residential-construction-service-success-story", destination: "/blog/newcomb-road-remodel-a-residential-construction-service-success-story", permanent: true },
      { source: "/los-angeles-residential-contractors-econstruct-builds-dreams", destination: "/blog/los-angeles-residential-contractors-econstruct-builds-dreams", permanent: true },
      { source: "/blueprint-for-success-why-you-need-the-right-residential-contractors-in-los-angeles-for-your-home-renovation", destination: "/blog/blueprint-for-success-why-you-need-the-right-residential-contractors-in-los-angeles-for-your-home-renovation", permanent: true },
      { source: "/build-an-adu-in-los-angeles-your-comprehensive-guide-econstruct", destination: "/blog/build-an-adu-in-los-angeles-your-comprehensive-guide-econstruct", permanent: true },
      { source: "/adu-permit-los-angeles-your-path-to-building-an-adu-in-the-city-of-angels", destination: "/blog/adu-permit-los-angeles-your-path-to-building-an-adu-in-the-city-of-angels", permanent: true },

      // Catchall: any remaining /portfolio/slug → /projects
      { source: "/portfolio/:slug*", destination: "/projects", permanent: true },
      {
        source: "/services/fire-rebuild",
        destination: "/services/fire-rebuild-contractor-los-angeles",
        permanent: true,
      },
      {
        source: "/services/luxury-modernization",
        destination: "/services/luxury-home-builder-los-angeles",
        permanent: true,
      },
      {
        source: "/services/custom-homes",
        destination: "/services/custom-home-construction-los-angeles",
        permanent: true,
      },
      {
        source: "/services/adu-construction",
        destination: "/services/home-additions-los-angeles",
        permanent: true,
      },
      {
        source: "/lot-walk",
        destination: "/private-lot-walk",
        permanent: false,
      },
      ...wordpressBlogRedirects,
      {
        source: "/luxury-home-builders-beverly-hills",
        destination: "/blog/luxury-home-builders-beverly-hills",
        permanent: true,
      },
      {
        source: "/custom-home-builders-bel-air-los-angeles",
        destination: "/blog/custom-home-builders-bel-air-los-angeles",
        permanent: true,
      },
      {
        source: "/luxury-home-builders-calabasas",
        destination: "/blog/luxury-home-builders-calabasas",
        permanent: true,
      },
      {
        source: "/luxury-home-builders-pacific-palisades",
        destination: "/blog/luxury-home-builders-pacific-palisades",
        permanent: true,
      },
      {
        source: "/luxury-home-builders-malibu",
        destination: "/blog/luxury-home-builders-malibu",
        permanent: true,
      },
      {
        source: "/custom-home-builders-hidden-hills",
        destination: "/blog/custom-home-builders-hidden-hills",
        permanent: true,
      },
      {
        source: "/luxury-home-builders-platinum-triangle-bel-air-holmby-hills-beverly-hills",
        destination: "/blog/luxury-home-builders-platinum-triangle-bel-air-holmby-hills-beverly-hills",
        permanent: true,
      },
      {
        // Renamed 2026-05-28: client (Frank) wants "insurance adjuster" targeting,
        // not "public adjuster". Permanent 308 redirect preserves any existing
        // backlinks / bookmarks to the old URL.
        source: "/for-public-adjusters",
        destination: "/for-insurance-adjusters",
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
